"""
Builds the Spanish (/) and English (/en/) pages of The K9 Boutique Hotel site.

Run it after editing index.html, CONFIG in js/main.js, or the SEO text below:

    py tools/build.py

index.html is the source: it holds every text in Spanish and English side by side.
This script:
  - writes the <head> search block of index.html (title, description, sharing tags,
    business details for Google)
  - copies the WhatsApp number and social links from CONFIG in js/main.js into the
    HTML, so Google and visitors without JavaScript can see them
  - writes en/index.html, the English page Google can find on its own
  - writes robots.txt, and sitemap.xml once SITE_URL is set
"""
import html
import json
import re
from pathlib import Path

# The live web address, without a trailing slash, e.g. "https://www.k9boutiquehotel.mx".
# Leave empty until the domain works; then set it and run this script again.
SITE_URL = "https://thek9boutiquehotel.com"

AREAS = [
    "Ixtlahuacán de los Membrillos", "Chapala", "Ajijic", "San Nicolás de Ibarra",
    "Santa Cruz de la Soledad", "San Antonio Tlayacapan", "Atequiza",
]

SEO = {
    "es": {
        "title": "Hotel para perros cerca de Chapala y Ajijic | The K9 Boutique Hotel",
        "description": "Hotel para perros y caminatas en manada sin correa, cerca de Chapala, Ajijic y "
                       "San Nicolás de Ibarra. Habitación propia y 20 años de experiencia. Cotiza por WhatsApp.",
        "business": "Hotel para perros con habitación propia y jardín grande, y caminatas diarias en manada "
                    "en la montaña, sin correa. Cerca del Lago de Chapala.",
        "services": ["Hotel para perros (pensión canina)", "Caminatas en manada (paseo de perros)"],
        "locale": "es_MX", "alt_locale": "en_US",
    },
    "en": {
        "title": "Dog Boarding & Pack Hikes near Ajijic | The K9 Boutique Hotel",
        "description": "Dog boarding and off-leash pack hikes near Ajijic, Chapala and San Nicolás de Ibarra. "
                       "Private rooms, a big yard and 20 years of experience. Get a quote on WhatsApp.",
        "business": "Dog boarding with a private room for every dog and a big yard, plus daily off-leash "
                    "pack hikes in the mountains near Lake Chapala.",
        "services": ["Dog boarding (dog hotel)", "Pack hikes (dog walking)"],
        "locale": "en_US", "alt_locale": "es_MX",
    },
}

# English text for attributes that are not inside <span class="en">
EN_ATTRS = {
    'aria-label="Principal"': 'aria-label="Main"',
    'aria-label="Menú"': 'aria-label="Menu"',
    'aria-label="Pie de página"': 'aria-label="Footer"',
    'aria-label="Foto"': 'aria-label="Photo"',
}
EN_GALLERY_ALT = {
    "Perros en el hotel": "Dogs at the hotel",
    "La manada en la montaña": "The pack in the mountains",
    "Perros caminando en la montaña": "Dogs hiking in the mountains",
    "Perros en una caminata": "Dogs on a hike",
    "Perros refrescándose en el agua": "Dogs cooling off in the water",
}

ROOT = Path(__file__).resolve().parent.parent
PAGE_PATH = {"es": "/", "en": "/en/"}


def read_config():
    js = (ROOT / "js" / "main.js").read_text(encoding="utf-8")
    block = re.search(r"const CONFIG = \{(.*?)\};", js, re.S).group(1)
    return dict(re.findall(r'(\w+):\s*"([^"]*)"', block))


def url(lang):
    return SITE_URL + PAGE_PATH[lang]


def seo_block(lang, cfg, prefix):
    t = SEO[lang]
    esc = lambda v: html.escape(v, quote=True)
    image = f"{SITE_URL}/img/og-image.png" if SITE_URL else f"{prefix}img/og-image.png"
    lines = [
        "  <!-- SEO:START (generated by tools/build.py; edit SEO text there) -->",
        f"  <title>{esc(t['title'])}</title>",
        f'  <meta name="description" content="{esc(t["description"])}">',
    ]
    if SITE_URL:
        lines += [
            f'  <link rel="canonical" href="{url(lang)}">',
            f'  <link rel="alternate" hreflang="es-MX" href="{url("es")}">',
            f'  <link rel="alternate" hreflang="en" href="{url("en")}">',
            f'  <link rel="alternate" hreflang="x-default" href="{url("es")}">',
        ]
    lines += [
        '  <meta property="og:type" content="website">',
        '  <meta property="og:site_name" content="The K9 Boutique Hotel">',
        f'  <meta property="og:locale" content="{t["locale"]}">',
        f'  <meta property="og:locale:alternate" content="{t["alt_locale"]}">',
        f'  <meta property="og:title" content="{esc(t["title"])}">',
        f'  <meta property="og:description" content="{esc(t["description"])}">',
    ]
    if SITE_URL:
        lines.append(f'  <meta property="og:url" content="{url(lang)}">')
    lines += [
        f'  <meta property="og:image" content="{image}">',
        '  <meta property="og:image:width" content="1200">',
        '  <meta property="og:image:height" content="630">',
    ]

    business = {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        "name": "The K9 Boutique Hotel",
        "description": t["business"],
        "telephone": "+" + cfg["whatsapp"],
        "image": image,
        "logo": f"{SITE_URL}/img/logo.png" if SITE_URL else f"{prefix}img/logo.png",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "Av. Acueducto 747",
            "addressLocality": "Ixtlahuacán de los Membrillos",
            "addressRegion": "Jalisco",
            "addressCountry": "MX",
        },
        "areaServed": [{"@type": "City", "name": a} for a in AREAS],
        "knowsLanguage": ["es", "en"],
        "hasOfferCatalog": {
            "@type": "OfferCatalog",
            "name": "Servicios" if lang == "es" else "Services",
            "itemListElement": [
                {"@type": "Offer", "itemOffered": {"@type": "Service", "name": s}} for s in t["services"]
            ],
        },
        "sameAs": [cfg["instagram"], cfg["facebook"]],
    }
    if SITE_URL:
        business = {**business, "@id": f"{SITE_URL}/#business", "url": url(lang)}
    data = json.dumps(business, ensure_ascii=False, indent=2).replace("</", "<\\/")
    lines.append('  <script type="application/ld+json">')
    lines += ["  " + line for line in data.splitlines()]
    lines += ["  </script>", "  <!-- SEO:END -->"]
    return "\n".join(lines)


def set_seo(page, block):
    return re.sub(r"  <!-- SEO:START.*?<!-- SEO:END -->", lambda m: block, page, count=1, flags=re.S)


def fill_contacts(page, cfg):
    wa = f"https://wa.me/{cfg['whatsapp']}"
    # every WhatsApp link points at the real number, even without JavaScript
    page = re.sub(r'<a href="[^"]*"(?=[^>]*\bdata-wa\b)', f'<a href="{wa}"', page)
    page = re.sub(r"(<a [^>]*\bdata-phone\b[^>]*>)[^<]*(</a>)", rf"\g<1>{cfg['phoneDisplay']}\g<2>", page)
    page = re.sub(r'<a href="[^"]*"([^>]*data-social="(\w+)")',
                  lambda m: f'<a href="{cfg[m.group(2)]}"{m.group(1)}', page)
    return page


def english(page, cfg):
    page = page.replace('<html lang="es">', '<html lang="en" data-root="../">', 1)
    # files live one folder up
    page = re.sub(r'\b(src|href|poster)="(img|video|css|js)/', r'\1="../\2/', page)
    # language switch: Spanish is one folder up, English is this page
    page = re.sub(r'<a href="[^"]*"( data-lang-link="es"[^>]*?)( aria-current="page")?>',
                  r'<a href="../"\1>', page)
    page = re.sub(r'<a href="[^"]*"( data-lang-link="en"[^>]*?)( aria-current="page")?>',
                  r'<a href="./"\1 aria-current="page">', page)
    # English alt text and titles
    page = re.sub(r'alt="[^"]*"(\s+data-alt-en="([^"]*)")', r'alt="\2"\1', page)
    page = re.sub(r'title="[^"]*"(\s+data-title-en="([^"]*)")', r'title="\2"\1', page)
    for es, en in EN_GALLERY_ALT.items():
        page = page.replace(f'alt="{es}"', f'alt="{en}"')
    for es, en in EN_ATTRS.items():
        page = page.replace(es, en)
    return set_seo(page, seo_block("en", cfg, "../"))


def main():
    cfg = read_config()
    src = ROOT / "index.html"
    page = fill_contacts(src.read_text(encoding="utf-8"), cfg)
    page = set_seo(page, seo_block("es", cfg, ""))
    src.write_text(page, encoding="utf-8", newline="\n")

    (ROOT / "en").mkdir(exist_ok=True)
    (ROOT / "en" / "index.html").write_text(english(page, cfg), encoding="utf-8", newline="\n")

    robots = "User-agent: *\nAllow: /\n"
    if SITE_URL:
        robots += f"\nSitemap: {SITE_URL}/sitemap.xml\n"
        alts = "".join(f'\n    <xhtml:link rel="alternate" hreflang="{h}" href="{url(l)}"/>'
                       for h, l in (("es-MX", "es"), ("en", "en"), ("x-default", "es")))
        entries = "".join(f"\n  <url>\n    <loc>{url(l)}</loc>{alts}\n  </url>" for l in ("es", "en"))
        sitemap = ('<?xml version="1.0" encoding="UTF-8"?>\n'
                   '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" '
                   'xmlns:xhtml="http://www.w3.org/1999/xhtml">' + entries + "\n</urlset>\n")
        (ROOT / "sitemap.xml").write_text(sitemap, encoding="utf-8", newline="\n")
    (ROOT / "robots.txt").write_text(robots, encoding="utf-8", newline="\n")

    print("Built index.html and en/index.html" + ("" if SITE_URL else
          "  (SITE_URL not set yet: no canonical/hreflang links or sitemap until the domain is added)"))


if __name__ == "__main__":
    main()
